import { writeFile, access, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'

const execFileAsync = promisify(execFile)

const GREEN = '\x1b[32m'
const YELLOW = '\x1b[33m'
const RED = '\x1b[31m'
const BOLD = '\x1b[1m'
const NC = '\x1b[0m'

const info = (msg) => console.log(`${GREEN}[✓]${NC} ${msg}`)
const warn = (msg) => console.log(`${YELLOW}[!]${NC} ${msg}`)

async function exists(path) {
  try { await access(path); return true } catch { return false }
}

export default async function setupTunnel(args, paths) {
  // Parse --domain argument
  const domainIdx = args.indexOf('--domain')
  const domain = domainIdx !== -1 ? args[domainIdx + 1] : null
  const port = args.includes('--port') ? args[args.indexOf('--port') + 1] : '3000'

  if (!domain) {
    console.log(`Usage: kenobot setup-tunnel --domain <subdomain.example.com> [--port 3000]\n`)
    console.log(`Generates a cloudflared tunnel config for exposing KenoBot's HTTP webhook.\n`)
    console.log(`Options:`)
    console.log(`  --domain  Hostname for the tunnel (required)`)
    console.log(`  --port    Local port to forward (default: 3000)`)
    process.exit(1)
  }

  // Check if cloudflared is installed
  let hasCloudflared = false
  try {
    await execFileAsync('which', ['cloudflared'])
    hasCloudflared = true
    info('cloudflared found')
  } catch {
    warn('cloudflared not found — install it first:')
    console.log(`  https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/\n`)
  }

  // Generate cloudflared config
  await mkdir(paths.config, { recursive: true })
  const configPath = join(paths.config, 'cloudflared.yml')

  const yaml = `# KenoBot Cloudflare Tunnel Configuration
# Generated by: kenobot setup-tunnel --domain ${domain}
#
# Before using this config:
# 1. cloudflared tunnel login
# 2. cloudflared tunnel create kenobot
# 3. cloudflared tunnel route dns kenobot ${domain}
# 4. Update credentials-file below with your tunnel ID

tunnel: kenobot
credentials-file: ~/.cloudflared/<tunnel-id>.json

ingress:
  - hostname: ${domain}
    service: http://localhost:${port}
  - service: http_status:404
`

  if (await exists(configPath)) {
    warn(`Config already exists: ${configPath}`)
    console.log(`  Delete it first to regenerate, or edit it manually.\n`)
  } else {
    await writeFile(configPath, yaml)
    info(`Config written: ${configPath}`)
  }

  // Print next steps
  console.log(`\n${BOLD}Next steps:${NC}\n`)

  if (!hasCloudflared) {
    console.log(`  1. Install cloudflared:`)
    console.log(`     curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared`)
    console.log(`     chmod +x /usr/local/bin/cloudflared\n`)
  }

  console.log(`  ${hasCloudflared ? '1' : '2'}. Authenticate with Cloudflare:`)
  console.log(`     cloudflared tunnel login\n`)

  console.log(`  ${hasCloudflared ? '2' : '3'}. Create the tunnel:`)
  console.log(`     cloudflared tunnel create kenobot\n`)

  console.log(`  ${hasCloudflared ? '3' : '4'}. Update credentials-file in ${configPath}`)
  console.log(`     Replace <tunnel-id> with the ID from the create command\n`)

  console.log(`  ${hasCloudflared ? '4' : '5'}. Route DNS:`)
  console.log(`     cloudflared tunnel route dns kenobot ${domain}\n`)

  console.log(`  ${hasCloudflared ? '5' : '6'}. Ensure KenoBot HTTP channel is enabled:`)
  console.log(`     HTTP_ENABLED=true`)
  console.log(`     HTTP_PORT=${port}`)
  console.log(`     WEBHOOK_SECRET=$(openssl rand -hex 32)\n`)

  console.log(`  ${hasCloudflared ? '6' : '7'}. Run the tunnel:`)
  console.log(`     cloudflared tunnel --config ${configPath} run\n`)

  console.log(`  ${BOLD}Optional:${NC} Install as systemd service:`)
  console.log(`     cloudflared service install`)
  console.log(`     sudo systemctl enable --now cloudflared`)
}
